### PR TITLE
Solutions

### PR DESCRIPTION
**Pull request by devikasugathan**

### CODE REVIEW

**Comment by vardhanrao** [comment]
@devikasugathan name the folder by Title of the issue not the issue number.

**Comment by notlmn** [comment]
@devikasugathan By the way, you don't have to create a new pull request to add the commits, just commit and push to the same branch that you pushed to before, they will show up here automatically!

**Review by notlmn — CHANGES_REQUESTED** [review]
As you may have seen that the problems and solutions are now separated into directories labelled by the approach used to solve the problem and difficulty.

All you have to do now it move the files into their respective directories.

You're just one change away from getting the PR merged, looking forward to your changes.

**Comment by devikasugathan** [comment]
Can I open a new pull request as I had an issue with my laptop and the changes were not getting updated

**Pull request closed without merging**
